In [1]:
import numpy as np

In [2]:
vet = np.array([1,2,3,4,5])

In [3]:
dir(vet)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [4]:
list = [1,2,3,4,5]

In [7]:
vet[0]

1

In [8]:
vet[4] = 1000

In [9]:
vet

array([   1,    2,    3,    4, 1000])

In [10]:
list[0]

1

In [12]:
list[0] = "oi"

In [13]:
print(vet.shape)

(5,)


In [14]:
vet2 = np.arange(0, 5.25, 0.25)

In [15]:
vet2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
vet3 = np.array([True, False, True])

In [21]:
vet3

array([ True, False,  True])

In [22]:
vet4 = np.array(["Python", "R"])

In [23]:
vet4

array(['Python', 'R'], dtype='<U6')

In [25]:
vet5 = np.linspace(0,5)

In [26]:
vet5

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [27]:
vet6 = np.linspace(0, 5, 10)

In [28]:
vet6

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
matriz = np.array([[1,2,3], [4,5,6]])

In [30]:
matriz.shape

(2, 3)

In [31]:
matriz2 = np.random.randn(4,4)

In [32]:
matriz2

array([[ 1.6602426 , -0.09003663, -0.18230272,  0.27954766],
       [-0.30833508,  0.16456239,  0.54267496, -0.07532322],
       [-0.22439295,  0.50978171, -0.80639587, -0.79815107],
       [ 0.40804332,  0.26252785, -0.33299762, -0.45937301]])

In [33]:
v= np.array([10,40,566,234,34])

In [34]:
v

array([ 10,  40, 566, 234,  34])

In [35]:
np.mean(v)

176.8

In [36]:
np.std(v)

210.55963525804276

In [37]:
np.var(v)

44335.36

In [38]:
np.sum(v)

884

In [39]:
np.prod(v)

1801238400

In [40]:
v2 = np.arange(10)

In [41]:
v2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
v2[1:9:2]

array([1, 3, 5, 7])

In [43]:
v2.min()

0

In [44]:
v2.max()

9

In [45]:
np.mean(v2)

4.5